name: Newsletter Bot          # ← a short, human‑readable title

on:                            # ← the events that trigger the workflow
  schedule:
    - cron: '0 13 * * FRI'     # every Friday at 9 AM Toronto (13:00 UTC)
  workflow_dispatch:           # allow manual runs from the Actions tab

jobs:
  build-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run newsletter bot
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python newsletter_bot.py
